name: Setup uv

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.24"
        python-version: ${{ matrix.python-version }}
