name: Publish Python 🐍 distributions 📦 to PyPI
on:
  release:
    types: [published]
defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/coqui-tts
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv
        uses: ./.github/actions/setup-uv
      - name: Verify tag matches version
        run: |
          set -ex
          version=$(grep -m 1 version pyproject.toml | grep -P '\d+\.\d+\.\d+' -o)
          tag="${GITHUB_REF/refs\/tags\/}"
          if [[ "v$version" != "$tag" ]]; then
            exit 1
          fi
      - name: Set up Python
        run: uv python install
      - name: Build sdist and wheel
        run: uv build
      - name: Test installation of sdist and wheel
        run: |
          uv venv --no-project
          uv pip install dist/*.tar.gz
          uv pip install dist/*.whl
      - name: Publish
        run: uv publish
